#pragma once

#include <QString>

#include <cstdint>

namespace cppforge::entities
{
    /**
     * @brief Encapsulates the outcome of evaluating a user's code submission.
     *
     * An ExecutionResult contains testing feedback such as standard output, runtime errors,
     * total execution time, and how many test cases were passed. This class acts as the final
     * report generated by the CodeRunner service.
     */
    class ExecutionResult
    {
    public:
        /**
         * @brief Default constructor for ExecutionResult.
         */
        ExecutionResult() = default;

        /**
         * @brief Constructs a fully populated ExecutionResult instance.
         *
         * @param submissionId The ID of the original submission this result belongs to.
         * @param isSuccess True if the submission passed all tests; otherwise false.
         * @param output The standard output captured during the program's execution.
         * @param errors The standard error or compilation errors captured during processing.
         * @param timeMs The total time consumed by the execution round in milliseconds.
         * @param passedTestsCount The total number of successful test case matches.
         */
        ExecutionResult(uint64_t submissionId, bool isSuccess, QString output, QString errors, int32_t timeMs,
                        uint32_t passedTestsCount);

        /**
         * @brief Retrieves the referenced submission identifier.
         * @return The submission ID as a 64-bit unsigned integer.
         */
        uint64_t getSubmissionId() const;

        /**
         * @brief Indicates whether the execution passed all criteria successfully.
         * @return True if the execution stringently met all evaluation criteria.
         */
        bool isSuccess() const;

        /**
         * @brief Retrieves the standard output streams captured during execution.
         * @return A constant reference to the QString representing the program's payload dump.
         */
        const QString &getOutput() const;

        /**
         * @brief Retrieves any logged exception, compilation, or runtime error texts.
         * @return A constant reference to the QString containing error outputs.
         */
        const QString &getErrors() const;

        /**
         * @brief Retrieves the total elapsed span of the script's execution process.
         * @return The elapsed time stored in a 32-bit integer structure, represented in milliseconds.
         */
        int32_t getTimeMs() const;

        /**
         * @brief Retrieves the quantitative measure of evaluating individual test cases successfully.
         * @return The passed test count as a 32-bit unsigned entity.
         */
        uint32_t getPassedTestsCount() const;

    private:
        uint64_t submissionId_;
        bool isSuccess_;
        QString output_;
        QString errors_;
        int32_t timeMs_;
        uint32_t passedTestsCount_;
    };
} // namespace cppforge::entities
