name: Release (Windows)

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSYS2 (Windows)
      uses: msys2/setup-msys2@v2
      with:
        msystem: UCRT64
        update: true
        install: >-
          mingw-w64-ucrt-x86_64-gcc
          mingw-w64-ucrt-x86_64-cmake
          mingw-w64-ucrt-x86_64-qt5-base
          mingw-w64-ucrt-x86_64-qt5-tools   
          mingw-w64-ucrt-x86_64-qt5-declarative
          mingw-w64-ucrt-x86_64-ninja
          mingw-w64-ucrt-x86_64-nsis
          
    - name: Ensure windeployqt exists
      shell: msys2 {0}
      run: |
        pacman -S --noconfirm mingw-w64-ucrt-x86_64-qt5-tools
        ls /ucrt64/bin | grep windeploy || echo "STILL NOT FOUND"
    - name: Configure CMake
      shell: msys2 {0}
      run: |          
        cmake -B build -G Ninja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH=/ucrt64

    - name: Build
      shell: msys2 {0}
      run: cmake --build build

    - name: Deploy Qt
      shell: msys2 {0}
      run: |
        which windeployqt || echo "NOT FOUND"
        find / -name "windeployqt.exe" 2>/dev/null || true
        windeployqt.exe $(find build -name "cppforge.exe")

    - name: Package (CPack)
      shell: msys2 {0}
      run: cmake --build build --target package

    - name: List files
      run: dir build

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: build/*.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
